### ISSUE TITLE
[TODO] Move to Go Module

### ISSUE THREAD

**Issue by bxcodec** [bxcodec/faker#54]
## Todo
Roadmap for go module faker/v3: 
### Chore

- [x]  Introduce new go module as new version: v/3.  (#56)
- [x] Apply linter for better quality. PR: (#55)

### Breaking changes

- [x] Fix typos that caused a breaking change. (#52 )

### Features

- [x] Optionally insert nils instead of empty slices and maps (#58, #59)
- [ ] Export a generator functions so that can accessed publicly (#45 #63)
- [x] Support length (#49, #60)

---
Really appreciate if anyone can help to submit any PR regarding to these issues.
